apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: git-clone
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/git-clone/git-clone.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: next-version
      runAfter:
      - git-clone
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/ml-python-gpu-training/release/next-version.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: jx-variables
      runAfter:
      - next-version
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/ml-python-gpu-training/release/jx-variables.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: build-flake8
      runAfter:
      - jx-variables
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/ml-python-gpu-training/release/build-flake8.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: build-training
      runAfter:
      - build-flake8
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/ml-python-gpu-training/release/build-training.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: build-export-model
      runAfter:
      - build-training
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/ml-python-gpu-training/release/build-export-model.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
  workspaces:
  - name: pipeline-ws
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
status: {}
