apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: jx-variables
spec:
  steps:
  - image: ghcr.io/jenkins-x/jx-boot:3.10.86
    name: ""
    resources:
      requests:
        cpu: 400m
        memory: 600Mi
    script: |
      #!/usr/bin/env sh
      jx gitops variables
      jx gitops pr variables
  workspaces:
  - name: source
