apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: promote-jx-preview
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
    workingDir: /workspace/source
  steps:
  - image: ghcr.io/jenkins-x-plugins/jx-preview:0.1.0
    name: ""
    resources: {}
    script: |
      #!/usr/bin/env sh
      source .jx/variables.sh
      jx preview create
