apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: git-clone-pr
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/git-clone/git-clone-pr.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: jx-variables
      runAfter:
      - git-clone-pr
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/ml-python-gpu-service/pullrequest/jx-variables.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: build-step2
      runAfter:
      - jx-variables
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/ml-python-gpu-service/pullrequest/build-step2.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: build-flake8
      runAfter:
      - build-step2
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/ml-python-gpu-service/pullrequest/build-flake8.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: build-testing
      runAfter:
      - build-flake8
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/ml-python-gpu-service/pullrequest/build-testing.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: check-registry
      runAfter:
      - build-testing
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/ml-python-gpu-service/pullrequest/check-registry.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: build-container-build
      runAfter:
      - check-registry
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/ml-python-gpu-service/pullrequest/build-container-build.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: promote-jx-preview
      runAfter:
      - build-container-build
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/ml-python-gpu-service/pullrequest/promote-jx-preview.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
  workspaces:
  - name: pipeline-ws
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
status: {}
