apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: git-clone
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/git-clone/git-clone.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: admin-log
      runAfter:
      - git-clone
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/environment/release/admin-log.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
  workspaces:
  - name: pipeline-ws
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
status: {}
