apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: git-clone-pr
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/git-clone/git-clone-pr.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: jx-variables
      runAfter:
      - git-clone-pr
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/javascript/pullrequest/jx-variables.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: build-npm-install
      runAfter:
      - jx-variables
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/javascript/pullrequest/build-npm-install.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: build-npm-test
      runAfter:
      - build-npm-install
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/javascript/pullrequest/build-npm-test.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: check-registry
      runAfter:
      - build-npm-test
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/javascript/pullrequest/check-registry.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: build-container-build
      runAfter:
      - check-registry
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/javascript/pullrequest/build-container-build.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
    - name: promote-jx-preview
      runAfter:
      - build-container-build
      taskRef:
        params:
        - name: url
          value: https://github.com/spring-financial-group/jx3-pipeline-catalog.git
        - name: revision
          value: master
        - name: pathInRepo
          value: tasks/javascript/pullrequest/promote-jx-preview.yaml
        resolver: git
      workspaces:
      - name: output
        workspace: pipeline-ws
  workspaces:
  - name: pipeline-ws
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
status: {}
